name: Merge Bot

on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@v0.4.4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        reviewers: false
        required-labels: ready
        checks_enabled: true
        method: squash
        delete_source_branch: true
